# Generated by Django 5.0.2 on 2025-12-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_adresse_alter_user_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendeuruser',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='entreprise',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registre_commerce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wilaya',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='ClientUser',
        ),
        migrations.DeleteModel(
            name='VendeurUser',
        ),
    ]
